name: Github CI/CD Development

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Notify success
        if: success()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.ECC_TG_CHAT_ID }}
        run: |
          MESSAGE="✅ Сборка и тестирование dance\\-cup\\-ui\\-dev прошли успешно"
          curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
            -d chat_id=$TELEGRAM_CHAT_ID \
            -d text="$MESSAGE" \
            -d parse_mode=MarkdownV2
      - name: Notify failure
        if: failure()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.ECC_TG_CHAT_ID }}
        run: |
          MESSAGE="❌ Сборка или тестирование dance\\-cup\\-ui\\-dev провалены"
          curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
            -d chat_id=$TELEGRAM_CHAT_ID \
            -d text="$MESSAGE" \
            -d parse_mode=MarkdownV2
  create-image:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/dance-cup-ui-dev:latest .
      - name: Push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/dance-cup-ui-dev:latest
      - name: Notify success
        if: success()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.ECC_TG_CHAT_ID }}
        run: |
          MESSAGE="✅ Образ dance\\-cup\\-ui\\-dev обновлён"
          curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
            -d chat_id=$TELEGRAM_CHAT_ID \
            -d text="$MESSAGE" \
            -d parse_mode=MarkdownV2
      - name: Notify failure
        if: failure()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.ECC_TG_CHAT_ID }}
        run: |
          MESSAGE="❌ Не удалось обновить образ dance\\-cup\\-ui\\-dev"
          curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage \
            -d chat_id=$TELEGRAM_CHAT_ID \
            -d text="$MESSAGE" \
            -d parse_mode=MarkdownV2