name: Github CD

#on:
#  push:
#    branches:
#      - master

on: [push]

jobs:
  create-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/dance-cup-ui:latest .
      - name: Push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/dance-cup-ui:latest